name: google_oauth2_client
version: 0.3.3
authors:
- Gerwin Sturm <scarygami@gmail.com>
- Adam Singer <financeCoding@gmail.com>
- Kevin Moore <kevin@thinkpixellab.com>
description: Library to use for Google OAuth2 authentication / Client-side flow
homepage: https://github.com/dart-gde/dart-google-oauth2-library
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  http: '>=0.9.0 <0.10.0'
  oauth2: '>=0.9.0 <0.10.0'
  path: '>=1.0.0 <1.1.0'
dev_dependencies:
  browser: '>=0.9.0 <0.10.0'
  hop: '>=0.28.3'
